### ISSUE TITLE
请教下怎么使用

### ISSUE THREAD

**Issue by xixihahaXXXXX** [Ras0N/QMCTrans#1]
新手膜拜，问下如何使用？

**Comment by Ras0N** [comment]
上排只有四个按钮啦，第一个是用来添加文件的，第二个选择存放文件的文件夹，会自动扫描文件夹下的文件，第三个是用来从列表里面删除多余的文件，第四个点一下就开始转换了，转换后的文件在加密文件夹下，和源文件同名。
抱歉这么久才看到
